### ISSUE TITLE
## Story: User should be able to start a new room [User Epic]

### ISSUE THREAD

**Issue by danbilokha** [jmelnich/tetris#9]
([User Epic](https://github.com/jmelnich/tetris/projects/1#card-25858941)) 
- [ ] By clicking on "Start the game" button a user creates a room and become as a "host" of the room 
- [ ] He can launch it as he pleases 
- [ ] In the end, he will be the only one to be able to restart it (At the time between the end of the current game and lunching the new one, a new user can join)
